version: "3.9"

networks:
  mern-net:
    name: ${network_name}

services:
  mongo:
    container_name: ${mongo_name}
    image: mongo:5.0.3
    restart: ${restart}
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ${mongo_path}:/data/db
    networks:
      - ${network_name}

  node:
    container_name: ${node_name}
    build:
      context: ${project_path}
      dockerfile: ${repository_path}/Dockerfile
    user: "node"
    restart: ${restart}
    ports:
      - ${node_host}:${node_port}:3000
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ${project_path}:/home/node/app
    networks:
      - ${network_name}
    command: "node ${node_args}"

  node_builder:
    container_name: ${node_builder_name}
    build:
      context: ${project_path}
      dockerfile: ${repository_path}/Dockerfile
    user: "node"
    restart: ${restart}
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ${project_path}:/home/node/app
    networks:
      - ${network_name}
    command: "bash -c 'npm install && npm run build:w'"
